In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os, sys

### 데이터 컬럼 정보

train.csv
  - ID: 실제 판매되고 있는 고유 ID
  - 제품: 제품 코드
  - 대분류: 제품의 대분류 코드
  - 중분류: 제품의 중분류 코드
  - 소분류: 제품의 소분류 코드
  - 2022-01-01 ~ 2023-04-04 : 실제 일별 판매량

sample_submission.csv
  - ID: 실제 판매되고 있는 고유 ID
  - 2023-04-05 ~ 2023-04-25 : 예측한 일별 판매량

sales.csv
  - ID : 실제 판매되고 있는 고유 ID
  - 제품 : 제품 코드
  - 대분류 : 제품의 대분류 코드
  - 중분류 : 제품의 중분류 코드
  - 소분류 : 제품의 소분류 코드
  - 브랜드 : 제품의 브랜드 코드
  - 2022-01-01 ~ 2023-04-04 : 실제 일별 총 판매금액

brand_keyword_cnt.csv
  - 브랜드 : 브랜드 코드
  - 2022-01-01 ~ 2023-04-04 : 브랜드의 연관키워드 언급량을 정규화한 일별 데이터

product_info.csv
  - 제품 : 제품 코드
  - 제품특성 : 제품 특성 데이터(Text)

In [4]:
# CSV 파일을 불러오기
data_path = "C:/Users/KimDongyoung/data/open (2)/train.csv"  # 원하는 파일 경로로 수정하세요
df = pd.read_csv(data_path)
df.head()

,ID,제품,대분류,중분류,소분류,브랜드,2022-01-01,2022-01-02,2022-01-03,2022-01-04,...,2023-03-26,2023-03-27,2023-03-28,2023-03-29,2023-03-30,2023-03-31,2023-04-01,2023-04-02,2023-04-03,2023-04-04
0,0,B002-00001-00001,B002-C001-0002,B002-C002-0007,B002-C003-0038,B002-00001,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,B002-00002-00001,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,1,3,2,0,0,2,0
2,2,B002-00002-00002,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,B002-00002-00003,B002-C001-0003,B002-C002-0008,B002-C003-0044,B002-00002,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,B002-00003-00001,B002-C001-0001,B002-C002-0001,B002-C003-0003,B002-00003,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
train = pd.read_csv(os.path.join("C:/Users/KimDongyoung/data/open (2)/", 'train.csv'))
sample_submission = pd.read_csv(os.path.join("C:/Users/KimDongyoung/data/open (2)/", 'sample_submission.csv'))
sales = pd.read_csv(os.path.join("C:/Users/KimDongyoung/data/open (2)/", 'sales.csv'))
product_info = pd.read_csv(os.path.join("C:/Users/KimDongyoung/data/open (2)/", 'product_info.csv'))
brand_keyword_cnt = pd.read_csv(os.path.join("C:/Users/KimDongyoung/data/open (2)/", 'brand_keyword_cnt.csv'))

In [16]:
sample_submission.head()
# train.head()
# sales.head()

,ID,2023-04-05,2023-04-06,2023-04-07,2023-04-08,2023-04-09,2023-04-10,2023-04-11,2023-04-12,2023-04-13,...,2023-04-16,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-22,2023-04-23,2023-04-24,2023-04-25
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
sales.columns

Index(['ID', '제품', '대분류', '중분류', '소분류', '브랜드', '2022-01-01', '2022-01-02',
       '2022-01-03', '2022-01-04',
       ...
       '2023-03-26', '2023-03-27', '2023-03-28', '2023-03-29', '2023-03-30',
       '2023-03-31', '2023-04-01', '2023-04-02', '2023-04-03', '2023-04-04'],
      dtype='object', length=465)

In [23]:
brand_keyword_cnt['브랜드'].nunique()
sales['브랜드'].nunique()
train['브랜드'].nunique()

3170

In [19]:
brand_keyword_cnt.head()

,브랜드,2022-01-01,2022-01-02,2022-01-03,2022-01-04,2022-01-05,2022-01-06,2022-01-07,2022-01-08,2022-01-09,...,2023-03-26,2023-03-27,2023-03-28,2023-03-29,2023-03-30,2023-03-31,2023-04-01,2023-04-02,2023-04-03,2023-04-04
0,B002-00001,0.84131,0.91383,1.450530,2.422390,1.871190,1.581080,1.232950,1.174930,1.145920,...,0.319110,0.391640,0.377130,0.49318,0.072520,0.29010,0.31911,0.232080,0.333620,0.44966
1,B002-00002,12.64868,20.27850,15.332170,12.750210,13.562510,13.707570,11.937910,15.564250,14.084710,...,10.269790,11.966920,10.646930,10.41485,10.487380,9.48651,9.28343,10.429350,11.154620,11.38671
2,B002-00003,0.33362,0.43516,0.362630,0.174060,0.217580,0.464170,0.420650,0.290100,0.377130,...,0.536690,0.696250,0.449660,0.39164,1.029880,0.49318,0.91383,0.797790,1.015370,0.88482
3,B002-00005,1.07339,1.71163,2.016240,1.914700,1.987230,2.146790,1.682620,1.378000,1.421520,...,2.219320,2.509420,2.872060,2.37888,2.030750,1.53756,1.34899,1.261960,2.320850,2.30635
4,B002-00006,0.00000,0.00000,0.188558,0.246574,0.246574,0.246574,0.377139,0.087012,0.261084,...,0.072526,0.290103,0.087012,0.00000,0.130542,0.00000,0.00000,0.072526,0.217577,0.00000

In [18]:
product_info.head()

                 제품                                               제품특성
0  B002-03509-00001  제품유형:일반식품 콜라겐 펩타이드:1000mg 종류:어류 분자량:300Da 섭취대상...
1  B002-02376-00001                                        700mg x 28정
2  B002-03735-00001  제품타입:정 섭취방법:물과 함께 섭취대상:성인남녀 섭취횟수:하루 두 번 1일 총 섭...
3  B002-03735-00003  제품타입:정 섭취방법:물과 함께 섭취대상:성인남녀 섭취횟수:하루 한 번 1일 총 섭...
4  B002-02769-00001  HCA:900mg 영양소 원료명(식약처고시):비타민B1 영양소 원료명(식약처고시):...