In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df1 = pd.read_csv('C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/질문리스트.csv')

In [5]:
df1

                               질문                       답변고려사항
0             ETF에 대해 얼마나 알고계신가요?                ETF에 대한 기초 정보
1  ETF 투자에서 중요한 요소가 무엇이라고 생각하시나요?        중요시여기는 요소를 고려한 ETF 추천
2               투자의 목표가 어떻게 되시나요?    목표에 맞는 ETF 추천(장/단기 투자 구분)
3          본인의 투자 성향을 어떻게 생각하시나요?               위험감수성향(변동성) 파악
4              선호하는 투자 방식이 있으신가요?     분산투자 및 위험감수성향 고려한 ETF 추천
5                투자 경험이 어떻게 되시나요?            중요시여기는 요소의 중요도 증가
6                    시드 머니를 적어주세요  종목 종가와 투자성향을 고려하여 투자 가이드 생성
7           선호하는 투자 기간이 어떻게 되시나요?                   장/단기 투자 구분
8                 관심있는 섹터가 있으신가요?          관심있는 섹터를 포함한 ETF 추천
9                  배당 수익을 중시하시나요?               배당금이 높은 ETF 추천

In [6]:
from langchain.chat_models import ChatOpenAI

c:\Users\KimDongyoung\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\chat_models\__init__.py:25: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. 	from pydantic.v1 import BaseModel

  from langchain.chat_models.base import init_chat_model
c:\Users\KimDongyoung\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)

In [ ]:
df2 = pd.read_csv('C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/질문리스트.csv')

In [15]:
df3 = pd.read_csv('C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/rag_text.csv')

In [16]:
df3

,ETF,ETF개별구성종목티커,외화증권영문명,외화증권한글명,보유종목타입,배당주기
0,AAPB,USD,US Dollars,프로셰어즈 울트라 반도체,EF,Monthly
1,GPIQ,USD,USD U.S. DOLLAR,프로셰어즈 울트라 반도체,EF,Monthly
2,GPIQ,QQQM,Invesco Nasdaq 100 ETF,인베스코 나스닥100,EF,Monthly
3,IEMG,SCC,SEMIRARA MINING AND POWER,프로셰어즈 울트라숏 컨슈머 서비스,EF,SemiAnnual
4,IEMG,DNL,D&L INDUSTRIES INC,위즈덤트리 전세계 미국제외 배당 성장,EF,SemiAnnual
...,...,...,...,...,...,...
62,GPIX,USD,USD U.S. DOLLAR,프로셰어즈 울트라 반도체,EF,Monthly
63,TSL,USD,US Dollars,프로셰어즈 울트라 반도체,EF,Monthly
64,NVD,USD,US Dollars,프로셰어즈 울트라 반도체,EF,Monthly
65,RYLD,RSSL,GLOBAL X RUSSELL 2000 ETF,루셀 2000,EF,Monthly
66,TMF,TLT,ISHARES 20+ YEAR TREASURY BD,아이셰어즈 20년 국채,EF,Quarterly

In [17]:
df_3 = pd.read_csv('C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/ETF_총집합.csv')

In [19]:
df_3

,ETF,1개월_수익율,3개월_수익율,MACD,RSI,1년_수익률,누적수익율(Z),정보비율(Z),샤프지수(Z),1년_배당수익,...,유출금액_분산,종목조회수,관심종목등록수,계좌수증감률,관심등록대비_매수계좌,단기수익,장기수익,변동성,유동성,관심도
0,AIYY,-4.206078,-4.234522,0.691721,81.122103,0.000000,0.106790,0.718323,0.181970,4.28400,...,4.388801e+02,2235,150,2.273351,0.380000,큰 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
1,AMZY,-4.186593,-1.523106,0.709374,81.165131,14.708866,11.412621,27.852952,7.497988,5.68320,...,4.387549e+02,1916,161,1.630706,0.472050,큰 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
2,APLY,0.701422,10.715625,0.637939,72.986316,8.655335,2.696522,7.697102,2.340439,4.19760,...,4.388697e+02,3332,211,4.348445,0.336493,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
3,AWAY,-3.351309,-2.612645,0.106688,78.571429,7.674073,18.184831,31.710462,12.202529,0.14468,...,4.388938e+02,519,18,4.031859,0.611111,큰 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
4,CIBR,0.061296,1.331835,-0.278446,55.610973,22.713763,71.530743,75.007385,46.480294,0.26480,...,-9.967420e+02,5672,238,7.739907,0.441176,단기수익이 거의 존재하지 않으며 과매도 상태에 속해있음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
5,DGRO,1.743663,4.024542,-0.102310,50.000000,17.887689,49.436391,47.043862,54.419386,1.17292,...,2.875523e-63,9226,374,8.486155,0.427807,단기수익이 거의 존재하지 않으며 과매도 상태에 속해있음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
6,DGRW,1.279233,5.799215,0.043910,77.837838,20.467724,63.091344,63.006343,70.134787,0.72000,...,5.894566e-10,10449,598,1.060803,0.468227,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
7,DIA,1.346542,3.426621,2.392343,78.934353,17.731793,52.155761,49.563671,59.307988,2.33256,...,1.418566e-01,18604,975,6.642877,0.256410,단기수익이 높지만 과매수 상태에 속해있음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
8,DIV,2.308732,4.593383,3.046042,69.343851,13.389096,18.677974,19.952600,20.250991,0.99600,...,1.425312e-03,599,18,8.582226,0.444444,단기수익이 높지만 과매수 상태에 속해있음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
9,DIVO,1.159983,3.488290,-0.134963,65.309898,14.014609,20.842807,17.372511,37.459773,1.90128,...,-2.196851e+02,5470,222,0.922023,0.333333,단기수익이 거의 존재하지 않으며 과매도 상태에 속해있음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
10,EETH,-8.640276,-6.518040,0.815938,88.792073,1.774009,88.852264,83.556334,51.958781,6.35184,...,4.386855e+02,1353,131,0.530362,0.297710,큰 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,장기적인 수익을 기대할 수 있으며 제법 높은 배당수익을 기대할 수 있음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입의 규모가 유출의 규모보다 큼,관심도가 매우 낮으며 매수의 감소 추세가 존재함
11,FBY,0.671664,1.047023,0.573738,72.763592,22.929016,14.258791,28.747141,10.328027,9.52320,...,4.388498e+02,1953,136,0.127588,0.455882,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,장기적으로 손실이 우려되지만 높은 배당수익을 기대할 수 있음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
12,GOOY,-3.446761,3.636900,0.720846,80.021169,3.963581,2.922450,9.051083,2.675042,5.99160,...,4.388721e+02,1401,139,0.550247,0.438849,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
13,IBB,2.230578,7.111220,-0.190712,65.573770,11.076200,32.528333,42.184989,23.822386,0.50396,...,3.567819e-16,7382,396,7.509587,0.444444,단기 수익을 기대할 수 있으며 과매수나 과매도 상태에 속하지 않음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출의 규모 변동이 큼,관심도가 매우 낮으며 매수의 감소 추세가 존재함
14,IHI,0.462405,0.966094,0.678932,73.665606,4.750788,14.356090,22.375357,12.258044,0.21176,...,-3.053256e-158,1474,66,10.719700,0.212121,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
15,IJH,0.790049,1.636307,0.573981,72.573824,16.366834,38.677265,47.033563,29.449989,0.64580,...,4.271311e+02,285,41,0.615259,0.658537,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유출의 규모가 유입의 규모보다 큼,관심도가 매우 낮으며 매수의 감소 추세가 존재함
16,IJR,2.151645,3.829953,0.545893,70.261022,12.773831,30.826954,44.141897,20.704178,1.54288,...,4.285102e+02,664,83,0.912966,0.289157,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
17,ITA,2.964897,5.133893,1.091521,74.789350,19.748966,63.030879,67.317596,52.924047,1.19560,...,1.185293e+00,5280,337,1.513814,0.418398,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
18,IVV,0.806684,6.103004,0.118680,66.942149,24.315449,75.438149,77.558625,74.809266,6.44452,...,4.562139e+02,47861,2036,8.037736,0.381631,단기수익이 거의 존재하지 않으며 과매도 상태에 속해있음,장기적인 수익을 기대할 수 있으며 제법 높은 배당수익을 기대할 수 있음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
19,IWM,1.838297,4.596270,0.652693,83.577713,14.466379,38.819900,52.781064,26.977173,2.24880,...,3.314365e-83,59903,2421,3.177813,0.548947,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 낮은 편이지만 거래 규모의 편차가 매우 큼,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
20,JEPI,1.039706,2.347634,1.179575,81.766055,11.581623,14.259079,14.469509,15.450423,3.47388,...,1.792269e-03,113635,3428,105.656001,0.687865,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 크지 않지만 매수의 증가 추세가 존재함
21,JEPQ,-1.236178,3.032717,0.452922,71.270161,21.364241,28.184478,30.482765,31.694010,5.12112,...,3.029713e-01,62966,1926,12.505839,0.807373,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 크지 않지만 매수의 증가 추세가 존재함
22,KLIP,-1.526405,-1.747916,0.729691,77.708978,12.242293,4.178818,6.085483,4.538110,4.81800,...,-1.631727e+00,3648,101,11.496110,0.910891,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 크지 않지만 매수의 증가 추세가 존재함
23,KRE,5.186561,8.279023,0.480319,65.093413,21.033092,54.217503,63.716705,21.213927,1.56756,...,4.177371e+02,4628,145,3.113937,0.544828,단기 수익을 기대할 수 있으며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
24,MGK,0.327318,8.822322,0.414606,88.365651,31.039171,88.354320,90.771977,69.598274,1.23480,...,2.929428e-01,5247,252,1.516154,0.464286,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
25,MOAT,2.126544,3.177073,0.162097,80.421687,15.235463,42.944695,44.848436,40.063985,0.72850,...,6.749349e-03,6165,280,1.693243,0.339286,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
26,NOBL,1.418830,-0.690843,1.014694,83.134447,11.317566,23.532719,23.453268,19.091140,2.20096,...,3.864753e-04,3464,240,7.627055,0.179167,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
27,NVDY,0.443557,20.427236,0.711485,73.711983,104.396032,39.382751,63.046590,14.016459,15.01440,...,4.377194e+02,47350,1389,2.169392,1.057595,단기 수익을 기대할 수 있으며 과매수나 과매도 상태에 속하지 않음,장기적인 수익을 기대할 수 있으며 매우 높은 배당수익을 기대할 수 있음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 크지 않지만 매수의 증가 추세가 존재함
28,OARK,-1.269230,0.578152,0.631684,76.135888,9.236810,5.522797,11.636475,2.617577,3.16080,...,4.388662e+02,1708,88,100.460034,0.522727,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 크지 않지만 매수의 증가 추세가 존재함
29,QQQ,-0.911136,6.413682,0.217942,55.000000,26.094786,76.425746,78.489718,56.245255,3.04600,...,1.220477e+00,523205,10141,20.220262,0.648851,단기수익이 거의 존재하지 않으며 과매도 상태에 속해있음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 낮은 편이지만 거래 규모의 편차가 매우 큼,거래규모가 크며 유입과 유출이 모두 일정하게 유출되고 있음,관심도가 매우 높음
30,QQQM,-0.861140,7.172792,-0.913516,64.185545,28.339211,85.329118,86.877693,62.907315,1.27960,...,5.808251e+00,110303,3536,2.433389,0.909502,단기수익이 거의 존재하지 않으며 과매도 상태에 속해있음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유출의 규모가 유입의 규모보다 큼,관심도가 크지 않지만 매수의 증가 추세가 존재함
31,RYLD,-0.237653,0.638517,0.413909,73.308011,3.912246,12.403166,13.186399,8.925518,1.92960,...,1.690950e+04,1546,93,2.076770,0.634409,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출의 규모 변동이 큼,관심도가 매우 낮으며 매수의 감소 추세가 존재함
32,SCHD,2.140100,3.165541,0.542441,87.925170,12.147028,21.568382,22.073575,27.771427,3.29640,...,2.289432e-05,370778,8000,84.058690,0.766250,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 손실이 우려되지만 일정한 배당수익을 기대할 수 있음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 높음
33,SKYY,0.141973,0.583376,0.294890,80.109489,20.998700,66.273874,69.372544,37.630778,0.04520,...,4.162945e-01,1743,97,7.914411,0.360825,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
34,SMH,-2.829105,9.823179,0.147731,83.582090,58.280703,95.300362,95.627033,74.690314,1.04270,...,2.226800e-02,38690,1253,2.008580,0.517159,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
35,SOXQ,-3.555149,8.363591,0.053169,75.609756,46.097357,97.273069,96.354120,55.928347,0.24372,...,9.734979e-01,17666,620,0.605547,0.391935,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
36,SOXX,-4.171083,7.283323,1.167635,79.945430,42.681017,95.954607,94.660762,49.367718,1.24132,...,2.126983e-03,185234,4152,1.005639,0.306358,작은 단기 손실이 우려되며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 높음
37,SPHD,3.106931,7.161732,0.055216,67.478769,20.749069,48.073348,48.844149,41.673712,1.57476,...,6.883934e-03,7594,341,3.870997,0.513196,단기 수익을 기대할 수 있으며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
38,SPLG,0.818686,6.339445,0.628102,78.192876,24.392597,73.453012,75.096003,74.526234,0.89128,...,4.229131e+00,117732,3380,276.815257,1.219231,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 높으며 매수의 증가 추세가 매우 가파름
39,SPY,0.529920,6.231171,1.775695,82.610790,24.777599,76.603046,78.364563,77.951864,7.03608,...,1.033042e+01,260527,7835,12.604323,0.596554,단기수익이 높지만 과매수 상태에 속해있음,장기적인 수익을 기대할 수 있으며 제법 높은 배당수익을 기대할 수 있음,변동성이 낮은 편이지만 거래 규모의 편차가 매우 큼,거래규모가 크며 유입과 유출이 모두 일정하게 유출되고 있음,관심도가 매우 높음
40,SPYD,3.421618,6.803690,2.279063,81.018819,19.162928,46.462011,51.559061,39.017422,1.94772,...,1.698524e-08,5247,283,1.083172,0.406360,단기수익이 높지만 과매수 상태에 속해있음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
41,SPYG,0.274185,8.738696,0.333360,81.067961,29.649326,85.264135,87.582165,73.600472,0.49672,...,7.134682e-02,18815,517,1.235314,0.829787,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 크지 않지만 매수의 증가 추세가 존재함
42,SPYV,1.501683,3.737891,-3.017262,53.525940,19.401959,56.836408,55.998303,59.365581,1.15104,...,2.666362e-07,2523,162,-0.219776,0.413580,단기수익이 거의 존재하지 않으며 매우 과매도 상태에 속해있음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
43,TSLY,-0.379070,13.134321,0.688251,74.939786,-11.813560,7.488170,11.511554,8.261366,11.59320,...,4.384463e+02,108652,1892,4.871676,0.965645,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,장기적으로 손실이 우려되지만 높은 배당수익을 기대할 수 있음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 크지 않지만 매수의 증가 추세가 존재함
44,VIG,1.442616,5.937141,0.185198,76.732468,13.915674,46.276988,43.913768,55.544712,3.59680,...,2.057314e-01,6950,405,1.802221,0.345679,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
45,VOO,0.614245,6.197668,1.941955,84.862385,23.561880,73.253054,74.537141,75.478175,7.13400,...,1.536767e+00,217779,6256,6.558188,0.714354,단기수익이 높지만 과매수 상태에 속해있음,장기적인 수익을 기대할 수 있으며 제법 높은 배당수익을 기대할 수 있음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 높음
46,VTI,0.559901,5.755915,0.288553,84.009009,23.760203,73.169279,74.806225,71.312009,3.80760,...,1.384374e-197,38915,1210,1.315151,0.626446,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
47,VYM,1.404605,3.794232,-0.094497,50.259067,17.743898,44.902446,41.928809,51.891382,4.09480,...,9.795107e-17,3066,208,6.922993,0.389423,단기수익이 거의 존재하지 않으며 과매도 상태에 속해있음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
48,XBI,3.138095,7.555421,-0.064219,56.637168,18.132755,61.462187,68.946038,29.361489,0.45912,...,4.476856e-03,27599,425,3.541159,0.621176,단기 수익을 기대할 수 있으며 과매수나 과매도 상태에 속하지 않음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 크며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
49,XLF,2.141520,4.392761,0.183957,78.000000,25.435414,79.154185,82.262036,73.783434,0.65120,...,2.132834e-01,5750,409,0.840205,0.383863,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 낮은 편이지만 거래 규모의 편차가 매우 큼,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
50,XLK,-1.104216,6.590240,-0.016424,73.852721,28.700734,85.688452,86.968088,57.540112,1.60000,...,1.586443e-10,12340,768,0.041649,0.281250,단기수익이 거의 존재하지 않으며 과매수나 과매도 상태에 속하지 않음,큰 장기적인 수익을 기대할 수 있지만 배당수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입의 규모가 유출의 규모보다 큼,관심도가 매우 낮으며 매수의 감소 추세가 존재함
51,XLP,1.606458,4.630217,3.413896,89.015788,11.702758,25.346779,25.814462,27.659160,2.32772,...,8.892204e-01,4265,253,-0.126580,0.328063,단기수익이 높지만 과매수 상태에 속해있음,장기적인 손실이 우려되며 배당 수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유출의 규모가 유입의 규모보다 큼,관심도가 매우 낮으며 매수의 감소 추세가 존재함
52,XLU,3.382696,7.153479,4.071493,70.977420,13.968511,35.264610,43.107675,26.185735,2.22032,...,1.906971e-01,9015,649,0.325277,0.397535,단기수익이 높지만 과매수 상태에 속해있음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 크며 다른 ETF와의 상관관계가 낮아 독립성이 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함
53,XLV,2.536791,5.072457,-0.187916,26.442308,14.068722,36.185026,35.254226,43.414759,2.29012,...,8.427263e-07,13939,768,1.218102,0.466146,단기수익이 거의 존재하지 않으며 매우 과매도 상태에 속해있음,장기수익이 거의 존재하지 않으며 배당수익이 낮음,변동성이 매우 낮으며 다른 ETF와의 상관관계가 높음,거래 규모가 크지 않으며 유입과 유출이 모두 일정하게 유지되고 있음,관심도가 매우 낮으며 매수의 감소 추세가 존재함

In [10]:
df4 = pd.read_csv('C:/Users/KimDongyoung/Desktop/my_git/mygit/NH투자증권/환율_s&p500.csv')
df4

,Unnamed: 0,날짜,s&p500 종가,s&p500 시가,s&p500 고가,s&p500 저가,s&p500 변동 %,환율 종가,환율 시가,환율 고가,환율 저가,환율 변동 %
0,63,2024- 05- 28,"5,306.04","5,315.91","5,315.91","5,280.89",0.02%,"1,362.42","1,361.69","1,364.63","1,355.27",0.18%
1,62,2024- 05- 29,"5,266.95","5,278.73","5,282.27","5,262.70",-0.74%,"1,370.08","1,363.87","1,372.04","1,361.14",0.56%
2,61,2024- 05- 30,"5,235.48","5,259.77","5,260.21","5,222.10",-0.60%,"1,374.74","1,371.46","1,382.32","1,369.08",0.34%
3,60,2024- 05- 31,"5,277.51","5,243.21","5,280.33","5,191.68",0.80%,"1,381.68","1,376.30","1,388.65","1,373.97",0.50%
4,59,2024- 06- 03,"5,283.40","5,297.15","5,302.11","5,234.32",0.11%,"1,370.36","1,383.10","1,383.80","1,371.17",-0.82%
...,...,...,...,...,...,...,...,...,...,...,...,...
59,4,2024- 08- 21,"5,620.85","5,603.09","5,632.68","5,591.57",0.42%,"1,332.76","1,329.29","1,340.50","1,326.22",0.39%
60,3,2024- 08- 22,"5,570.64","5,637.77","5,643.22","5,560.95",-0.89%,"1,341.29","1,334.28","1,344.31","1,331.39",0.64%
61,2,2024- 08- 23,"5,634.61","5,602.49","5,641.82","5,585.16",1.15%,"1,323.43","1,342.70","1,344.07","1,323.35",-1.33%
62,1,2024- 08- 26,"5,616.84","5,639.66","5,651.62","5,602.34",-0.32%,"1,327.48","1,324.78","1,329.95","1,317.81",0.31%
63,0,2024- 08- 27,"5,625.80","5,602.89","5,631.18","5,593.48",0.16%,"1,325.77","1,328.65","1,335.54","1,326.50",-0.13%

In [14]:
def df_to_text(df):
  text = ""
  for index, row in df.iterrows():
    text += f"{row['날짜']}의 S&P500 종가는 {row['s&p500 종가']}이며 S&P500 시가는 {row['s&p500 시가']}를 기록했습니다. S&P500 고가는 {row['s&p500 고가']}였고 S&P500 저가: {row['s&p500 저가']}입니다. S&P500 변동 퍼센티지는 {row['s&p500 변동 %']}이고, 환율 종가는 {row['환율 종가']}입니다. 환율 시가는 {row['환율 시가']}입니다. 환율 고가는 {row['환율 고가']}이며 환율 저가는 {row['환율 저가']}입니다. 환율 변동은 {row['환율 변동 %']}입니다.\n"
  return text

df4_text = df_to_text(df4)
print(df4_text)

2024- 05- 28의 S&P500 종가는 5,306.04이며 S&P500 시가는 5,315.91를 기록했습니다. S&P500 고가는 5,315.91였고 S&P500 저가: 5,280.89입니다. S&P500 변동 퍼센티지는 0.02%이고, 환율 종가는 1,362.42입니다. 환율 시가는 1,361.69입니다. 환율 고가는 1,364.63이며 환율 저가는 1,355.27입니다. 환율 변동은 0.18%입니다.
2024- 05- 29의 S&P500 종가는 5,266.95이며 S&P500 시가는 5,278.73를 기록했습니다. S&P500 고가는 5,282.27였고 S&P500 저가: 5,262.70입니다. S&P500 변동 퍼센티지는 -0.74%이고, 환율 종가는 1,370.08입니다. 환율 시가는 1,363.87입니다. 환율 고가는 1,372.04이며 환율 저가는 1,361.14입니다. 환율 변동은 0.56%입니다.
2024- 05- 30의 S&P500 종가는 5,235.48이며 S&P500 시가는 5,259.77를 기록했습니다. S&P500 고가는 5,260.21였고 S&P500 저가: 5,222.10입니다. S&P500 변동 퍼센티지는 -0.60%이고, 환율 종가는 1,374.74입니다. 환율 시가는 1,371.46입니다. 환율 고가는 1,382.32이며 환율 저가는 1,369.08입니다. 환율 변동은 0.34%입니다.
2024- 05- 31의 S&P500 종가는 5,277.51이며 S&P500 시가는 5,243.21를 기록했습니다. S&P500 고가는 5,280.33였고 S&P500 저가: 5,191.68입니다. S&P500 변동 퍼센티지는 0.80%이고, 환율 종가는 1,381.68입니다. 환율 시가는 1,376.30입니다. 환율 고가는 1,388.65이며 환율 저가는 1,373.97입니다. 환율 변동은 0.50%입니다.
2024- 06- 03의 S&P500 종가는 5,283.40이며 S&P500 시가는 5,297.15를 기록했습니다. S&P500 고가는 5,302.11였고 S&P500 저가: 5,234.32입니다. S&P500 변동 퍼센티지는 0.11%이고, 환율 종가는 1,370.36입니다. 환율 시가는 1,383.10입니다. 환율 고가는 1,383.80이며 환율 저가는 1,371.17입니다. 환율 변동은 -0.82%입니다.
2024- 06- 04의 S&P500 종가는 5,291.34이며 S&P500 시가는 5,278.24를 기록했습니다. S&P500 고가는 5,298.80였고 S&P500 저가: 5,257.63입니다. S&P500 변동 퍼센티지는 0.15%이고, 환율 종가는 1,372.93입니다. 환율 시가는 1,371.70입니다. 환율 고가는 1,379.18이며 환율 저가는 1,368.91입니다. 환율 변동은 0.19%입니다.
2024- 06- 05의 S&P500 종가는 5,354.03이며 S&P500 시가는 5,314.48를 기록했습니다. S&P500 고가는 5,354.16였고 S&P500 저가: 5,297.64입니다. S&P500 변동 퍼센티지는 1.18%이고, 환율 종가는 1,368.48입니다. 환율 시가는 1,374.42입니다. 환율 고가는 1,378.06이며 환율 저가는 1,367.26입니다. 환율 변동은 -0.32%입니다.
2024- 06- 06의 S&P500 종가는 5,352.96이며 S&P500 시가는 5,357.80를 기록했습니다. S&P500 고가는 5,362.35였고 S&P500 저가: 5,335.36입니다. S&P500 변동 퍼센티지는 -0.02%이고, 환율 종가는 1,363.71입니다. 환율 시가는 1,369.85입니다. 환율 고가는 1,370.90이며 환율 저가는 1,364.00입니다. 환율 변동은 -0.35%입니다.
2024- 06- 07의 S&P500 종가는 5,346.99이며 S&P500 시가는 5,343.81를 기록했습니다. S&P500 고가는 5,375.08였고 S&P500 저가: 5,331.33입니다. S&P500 변동 퍼센티지는 -0.11%이고, 환율 종가는 1,378.80입니다. 환율 시가는 1,364.61입니다. 환율 고가는 1,380.67이며 환율 저가는 1,363.15입니다. 환율 변동은 1.11%입니다.
2024- 06- 10의 S&P500 종가는 5,360.79이며 S&P500 시가는 5,341.22를 기록했습니다. S&P500 고가는 5,365.79였고 S&P500 저가: 5,331.52입니다. S&P500 변동 퍼센티지는 0.26%이고, 환율 종가는 1,373.60입니다. 환율 시가는 1,380.06입니다. 환율 고가는 1,383.31이며 환율 저가는 1,373.80입니다. 환율 변동은 -0.38%입니다.
2024- 06- 11의 S&P500 종가는 5,375.32이며 S&P500 시가는 5,353.00를 기록했습니다. S&P500 고가는 5,375.95였고 S&P500 저가: 5,327.25입니다. S&P500 변동 퍼센티지는 0.27%이고, 환율 종가는 1,377.50입니다. 환율 시가는 1,374.81입니다. 환율 고가는 1,381.39이며 환율 저가는 1,374.55입니다. 환율 변동은 0.28%입니다.
2024- 06- 12의 S&P500 종가는 5,421.03이며 S&P500 시가는 5,409.13를 기록했습니다. S&P500 고가는 5,447.25였고 S&P500 저가: 5,409.13입니다. S&P500 변동 퍼센티지는 0.85%이고, 환율 종가는 1,369.84입니다. 환율 시가는 1,378.70입니다. 환율 고가는 1,381.26이며 환율 저가는 1,363.59입니다. 환율 변동은 -0.56%입니다.
2024- 06- 13의 S&P500 종가는 5,433.74이며 S&P500 시가는 5,441.93를 기록했습니다. S&P500 고가는 5,441.93였고 S&P500 저가: 5,402.51입니다. S&P500 변동 퍼센티지는 0.23%이고, 환율 종가는 1,375.35입니다. 환율 시가는 1,371.08입니다. 환율 고가는 1,378.97이며 환율 저가는 1,365.58입니다. 환율 변동은 0.40%입니다.
2024- 06- 14의 S&P500 종가는 5,431.60이며 S&P500 시가는 5,424.08를 기록했습니다. S&P500 고가는 5,432.39였고 S&P500 저가: 5,403.75입니다. S&P500 변동 퍼센티지는 -0.04%이고, 환율 종가는 1,381.84입니다. 환율 시가는 1,376.47입니다. 환율 고가는 1,387.43이며 환율 저가는 1,374.67입니다. 환율 변동은 0.47%입니다.
2024- 06- 17의 S&P500 종가는 5,473.23이며 S&P500 시가는 5,431.11를 기록했습니다. S&P500 고가는 5,488.50였고 S&P500 저가: 5,420.40입니다. S&P500 변동 퍼센티지는 0.77%이고, 환율 종가는 1,378.46입니다. 환율 시가는 1,383.31입니다. 환율 고가는 1,384.41이며 환율 저가는 1,377.81입니다. 환율 변동은 -0.24%입니다.
2024- 06- 18의 S&P500 종가는 5,487.03이며 S&P500 시가는 5,476.15를 기록했습니다. S&P500 고가는 5,490.38였고 S&P500 저가: 5,471.32입니다. S&P500 변동 퍼센티지는 0.25%이고, 환율 종가는 1,378.64입니다. 환율 시가는 1,379.94입니다. 환율 고가는 1,385.97이며 환율 저가는 1,377.63입니다. 환율 변동은 0.01%입니다.
2024- 06- 20의 S&P500 종가는 5,473.17이며 S&P500 시가는 5,499.99를 기록했습니다. S&P500 고가는 5,505.53였고 S&P500 저가: 5,455.56입니다. S&P500 변동 퍼센티지는 -0.25%이고, 환율 종가는 1,391.93입니다. 환율 시가는 1,382.45입니다. 환율 고가는 1,393.56이며 환율 저가는 1,380.03입니다. 환율 변동은 0.79%입니다.
2024- 06- 21의 S&P500 종가는 5,464.62이며 S&P500 시가는 5,466.77를 기록했습니다. S&P500 고가는 5,478.31였고 S&P500 저가: 5,452.03입니다. S&P500 변동 퍼센티지는 -0.16%이고, 환율 종가는 1,387.01입니다. 환율 시가는 1,392.64입니다. 환율 고가는 1,393.94이며 환율 저가는 1,385.92입니다. 환율 변동은 -0.35%입니다.
2024- 06- 24의 S&P500 종가는 5,447.87이며 S&P500 시가는 5,459.58를 기록했습니다. S&P500 고가는 5,490.66였고 S&P500 저가: 5,447.59입니다. S&P500 변동 퍼센티지는 -0.31%이고, 환율 종가는 1,386.37입니다. 환율 시가는 1,388.95입니다. 환율 고가는 1,393.22이며 환율 저가는 1,384.48입니다. 환율 변동은 -0.05%입니다.
2024- 06- 25의 S&P500 종가는 5,469.30이며 S&P500 시가는 5,460.73를 기록했습니다. S&P500 고가는 5,472.88였고 S&P500 저가: 5,446.56입니다. S&P500 변동 퍼센티지는 0.39%이고, 환율 종가는 1,390.44입니다. 환율 시가는 1,386.79입니다. 환율 고가는 1,392.64이며 환율 저가는 1,383.85입니다. 환율 변동은 0.29%입니다.
2024- 06- 26의 S&P500 종가는 5,477.90이며 S&P500 시가는 5,460.71를 기록했습니다. S&P500 고가는 5,483.14였고 S&P500 저가: 5,451.87입니다. S&P500 변동 퍼센티지는 0.16%이고, 환율 종가는 1,392.90입니다. 환율 시가는 1,391.58입니다. 환율 고가는 1,395.25이며 환율 저가는 1,387.66입니다. 환율 변동은 0.18%입니다.
2024- 06- 27의 S&P500 종가는 5,482.87이며 S&P500 시가는 5,473.59를 기록했습니다. S&P500 고가는 5,490.81였고 S&P500 저가: 5,467.54입니다. S&P500 변동 퍼센티지는 0.09%이고, 환율 종가는 1,386.35입니다. 환율 시가는 1,394.31입니다. 환율 고가는 1,395.77이며 환율 저가는 1,383.49입니다. 환율 변동은 -0.47%입니다.
2024- 06- 28의 S&P500 종가는 5,460.48이며 S&P500 시가는 5,488.48를 기록했습니다. S&P500 고가는 5,523.64였고 S&P500 저가: 5,451.12입니다. S&P500 변동 퍼센티지는 -0.41%이고, 환율 종가는 1,380.73입니다. 환율 시가는 1,387.71입니다. 환율 고가는 1,390.18이며 환율 저가는 1,374.64입니다. 환율 변동은 -0.41%입니다.
2024- 07- 01의 S&P500 종가는 5,475.09이며 S&P500 시가는 5,471.08를 기록했습니다. S&P500 고가는 5,479.55였고 S&P500 저가: 5,446.53입니다. S&P500 변동 퍼센티지는 0.27%이고, 환율 종가는 1,382.50입니다. 환율 시가는 1,381.28입니다. 환율 고가는 1,385.57이며 환율 저가는 1,377.29입니다. 환율 변동은 0.13%입니다.
2024- 07- 02의 S&P500 종가는 5,509.01이며 S&P500 시가는 5,461.84를 기록했습니다. S&P500 고가는 5,509.69였고 S&P500 저가: 5,458.43입니다. S&P500 변동 퍼센티지는 0.62%이고, 환율 종가는 1,386.03입니다. 환율 시가는 1,383.53입니다. 환율 고가는 1,390.82이며 환율 저가는 1,381.87입니다. 환율 변동은 0.26%입니다.
2024- 07- 03의 S&P500 종가는 5,537.02이며 S&P500 시가는 5,507.44를 기록했습니다. S&P500 고가는 5,539.27였고 S&P500 저가: 5,507.42입니다. S&P500 변동 퍼센티지는 0.51%이고, 환율 종가는 1,386.80입니다. 환율 시가는 1,386.73입니다. 환율 고가는 1,392.65이며 환율 저가는 1,381.54입니다. 환율 변동은 0.06%입니다.
2024- 07- 05의 S&P500 종가는 5,567.19이며 S&P500 시가는 5,537.91를 기록했습니다. S&P500 고가는 5,570.33였고 S&P500 저가: 5,531.63입니다. S&P500 변동 퍼센티지는 0.54%이고, 환율 종가는 1,376.57입니다. 환율 시가는 1,380.32입니다. 환율 고가는 1,384.33이며 환율 저가는 1,376.14입니다. 환율 변동은 -0.26%입니다.
2024- 07- 08의 S&P500 종가는 5,572.85이며 S&P500 시가는 5,572.75를 기록했습니다. S&P500 고가는 5,583.11였고 S&P500 저가: 5,562.51입니다. S&P500 변동 퍼센티지는 0.10%이고, 환율 종가는 1,383.27입니다. 환율 시가는 1,377.51입니다. 환율 고가는 1,386.00이며 환율 저가는 1,376.45입니다. 환율 변동은 0.49%입니다.
2024- 07- 09의 S&P500 종가는 5,576.98이며 S&P500 시가는 5,584.24를 기록했습니다. S&P500 고가는 5,590.75였고 S&P500 저가: 5,574.57입니다. S&P500 변동 퍼센티지는 0.07%이고, 환율 종가는 1,382.92입니다. 환율 시가는 1,384.18입니다. 환율 고가는 1,387.24이며 환율 저가는 1,380.66입니다. 환율 변동은 -0.03%입니다.
2024- 07- 10의 S&P500 종가는 5,633.91이며 S&P500 시가는 5,591.26를 기록했습니다. S&P500 고가는 5,635.39였고 S&P500 저가: 5,586.44입니다. S&P500 변동 퍼센티지는 1.02%이고, 환율 종가는 1,382.81입니다. 환율 시가는 1,383.86입니다. 환율 고가는 1,388.38이며 환율 저가는 1,382.08입니다. 환율 변동은 -0.01%입니다.
2024- 07- 11의 S&P500 종가는 5,584.54이며 S&P500 시가는 5,635.21를 기록했습니다. S&P500 고가는 5,642.45였고 S&P500 저가: 5,576.53입니다. S&P500 변동 퍼센티지는 -0.88%이고, 환율 종가는 1,370.96입니다. 환율 시가는 1,383.94입니다. 환율 고가는 1,384.84이며 환율 저가는 1,369.82입니다. 환율 변동은 -0.86%입니다.
2024- 07- 12의 S&P500 종가는 5,615.35이며 S&P500 시가는 5,590.76를 기록했습니다. S&P500 고가는 5,655.56였고 S&P500 저가: 5,590.44입니다. S&P500 변동 퍼센티지는 0.55%이고, 환율 종가는 1,373.67입니다. 환율 시가는 1,372.30입니다. 환율 고가는 1,380.27이며 환율 저가는 1,369.54입니다. 환율 변동은 0.20%입니다.
2024- 07- 15의 S&P500 종가는 5,631.22이며 S&P500 시가는 5,638.16를 기록했습니다. S&P500 고가는 5,666.94였고 S&P500 저가: 5,614.75입니다. S&P500 변동 퍼센티지는 0.28%이고, 환율 종가는 1,384.17입니다. 환율 시가는 1,375.13입니다. 환율 고가는 1,386.17이며 환율 저가는 1,374.38입니다. 환율 변동은 0.76%입니다.
2024- 07- 16의 S&P500 종가는 5,667.20이며 S&P500 시가는 5,644.09를 기록했습니다. S&P500 고가는 5,669.67였고 S&P500 저가: 5,639.02입니다. S&P500 변동 퍼센티지는 0.64%이고, 환율 종가는 1,382.77입니다. 환율 시가는 1,385.31입니다. 환율 고가는 1,387.97이며 환율 저가는 1,381.60입니다. 환율 변동은 -0.10%입니다.
2024- 07- 17의 S&P500 종가는 5,588.27이며 S&P500 시가는 5,610.07를 기록했습니다. S&P500 고가는 5,622.49였고 S&P500 저가: 5,584.81입니다. S&P500 변동 퍼센티지는 -1.39%이고, 환율 종가는 1,378.51입니다. 환율 시가는 1,383.84입니다. 환율 고가는 1,384.95이며 환율 저가는 1,375.45입니다. 환율 변동은 -0.31%입니다.
2024- 07- 18의 S&P500 종가는 5,544.59이며 S&P500 시가는 5,608.56를 기록했습니다. S&P500 고가는 5,614.05였고 S&P500 저가: 5,522.81입니다. S&P500 변동 퍼센티지는 -0.78%이고, 환율 종가는 1,384.48입니다. 환율 시가는 1,379.67입니다. 환율 고가는 1,387.05이며 환율 저가는 1,375.78입니다. 환율 변동은 0.43%입니다.
2024- 07- 19의 S&P500 종가는 5,505.00이며 S&P500 시가는 5,543.37를 기록했습니다. S&P500 고가는 5,557.50였고 S&P500 저가: 5,497.04입니다. S&P500 변동 퍼센티지는 -0.71%이고, 환율 종가는 1,388.79입니다. 환율 시가는 1,386.01입니다. 환율 고가는 1,392.11이며 환율 저가는 1,383.65입니다. 환율 변동은 0.31%입니다.
2024- 07- 22의 S&P500 종가는 5,564.41이며 S&P500 시가는 5,544.54를 기록했습니다. S&P500 고가는 5,570.36였고 S&P500 저가: 5,529.04입니다. S&P500 변동 퍼센티지는 1.08%이고, 환율 종가는 1,386.99입니다. 환율 시가는 1,389.83입니다. 환율 고가는 1,391.10이며 환율 저가는 1,386.60입니다. 환율 변동은 -0.13%입니다.
2024- 07- 23의 S&P500 종가는 5,555.74이며 S&P500 시가는 5,565.30를 기록했습니다. S&P500 고가는 5,585.34였고 S&P500 저가: 5,550.90입니다. S&P500 변동 퍼센티지는 -0.16%이고, 환율 종가는 1,384.59입니다. 환율 시가는 1,387.99입니다. 환율 고가는 1,389.08이며 환율 저가는 1,382.04입니다. 환율 변동은 -0.17%입니다.
2024- 07- 24의 S&P500 종가는 5,427.13이며 S&P500 시가는 5,505.84를 기록했습니다. S&P500 고가는 5,508.04였고 S&P500 저가: 5,419.98입니다. S&P500 변동 퍼센티지는 -2.31%이고, 환율 종가는 1,382.17입니다. 환율 시가는 1,386.05입니다. 환율 고가는 1,388.90이며 환율 저가는 1,378.76입니다. 환율 변동은 -0.17%입니다.
2024- 07- 25의 S&P500 종가는 5,399.22이며 S&P500 시가는 5,428.70를 기록했습니다. S&P500 고가는 5,491.59였고 S&P500 저가: 5,390.95입니다. S&P500 변동 퍼센티지는 -0.51%이고, 환율 종가는 1,382.22입니다. 환율 시가는 1,383.75입니다. 환율 고가는 1,388.93이며 환율 저가는 1,379.20입니다. 환율 변동은 0.00%입니다.
2024- 07- 26의 S&P500 종가는 5,459.10이며 S&P500 시가는 5,433.67를 기록했습니다. S&P500 고가는 5,488.32였고 S&P500 저가: 5,430.70입니다. S&P500 변동 퍼센티지는 1.11%이고, 환율 종가는 1,383.72입니다. 환율 시가는 1,383.73입니다. 환율 고가는 1,388.53이며 환율 저가는 1,381.10입니다. 환율 변동은 0.11%입니다.
2024- 07- 29의 S&P500 종가는 5,463.54이며 S&P500 시가는 5,476.55를 기록했습니다. S&P500 고가는 5,487.74였고 S&P500 저가: 5,444.44입니다. S&P500 변동 퍼센티지는 0.08%이고, 환율 종가는 1,380.57입니다. 환율 시가는 1,384.82입니다. 환율 고가는 1,387.39이며 환율 저가는 1,379.69입니다. 환율 변동은 -0.23%입니다.
2024- 07- 30의 S&P500 종가는 5,436.44이며 S&P500 시가는 5,478.73를 기록했습니다. S&P500 고가는 5,489.46였고 S&P500 저가: 5,401.70입니다. S&P500 변동 퍼센티지는 -0.50%이고, 환율 종가는 1,382.81입니다. 환율 시가는 1,381.84입니다. 환율 고가는 1,387.04이며 환율 저가는 1,379.39입니다. 환율 변동은 0.16%입니다.
2024- 07- 31의 S&P500 종가는 5,522.30이며 S&P500 시가는 5,505.59를 기록했습니다. S&P500 고가는 5,551.51였고 S&P500 저가: 5,493.75입니다. S&P500 변동 퍼센티지는 1.58%이고, 환율 종가는 1,369.08입니다. 환율 시가는 1,384.32입니다. 환율 고가는 1,386.72이며 환율 저가는 1,366.79입니다. 환율 변동은 -0.99%입니다.
2024- 08- 01의 S&P500 종가는 5,446.68이며 S&P500 시가는 5,537.84를 기록했습니다. S&P500 고가는 5,566.16였고 S&P500 저가: 5,410.42입니다. S&P500 변동 퍼센티지는 -1.37%이고, 환율 종가는 1,369.08입니다. 환율 시가는 1,369.18입니다. 환율 고가는 1,371.65이며 환율 저가는 1,360.93입니다. 환율 변동은 0.00%입니다.
2024- 08- 02의 S&P500 종가는 5,346.56이며 S&P500 시가는 5,376.63를 기록했습니다. S&P500 고가는 5,383.89였고 S&P500 저가: 5,302.03입니다. S&P500 변동 퍼센티지는 -1.84%이고, 환율 종가는 1,356.63입니다. 환율 시가는 1,370.39입니다. 환율 고가는 1,378.80이며 환율 저가는 1,357.31입니다. 환율 변동은 -0.91%입니다.
2024- 08- 05의 S&P500 종가는 5,186.33이며 S&P500 시가는 5,151.14를 기록했습니다. S&P500 고가는 5,250.89였고 S&P500 저가: 5,119.26입니다. S&P500 변동 퍼센티지는 -3.00%이고, 환율 종가는 1,366.40입니다. 환율 시가는 1,358.14입니다. 환율 고가는 1,374.40이며 환율 저가는 1,354.48입니다. 환율 변동은 0.72%입니다.
2024- 08- 06의 S&P500 종가는 5,240.03이며 S&P500 시가는 5,206.42를 기록했습니다. S&P500 고가는 5,312.34였고 S&P500 저가: 5,193.56입니다. S&P500 변동 퍼센티지는 1.04%이고, 환율 종가는 1,374.52입니다. 환율 시가는 1,368.14입니다. 환율 고가는 1,380.49이며 환율 저가는 1,365.78입니다. 환율 변동은 0.59%입니다.
2024- 08- 07의 S&P500 종가는 5,199.50이며 S&P500 시가는 5,293.13를 기록했습니다. S&P500 고가는 5,330.64였고 S&P500 저가: 5,195.54입니다. S&P500 변동 퍼센티지는 -0.77%이고, 환율 종가는 1,374.47입니다. 환율 시가는 1,375.65입니다. 환율 고가는 1,379.61이며 환율 저가는 1,372.67입니다. 환율 변동은 0.00%입니다.
2024- 08- 08의 S&P500 종가는 5,319.31이며 S&P500 시가는 5,252.57를 기록했습니다. S&P500 고가는 5,328.03였고 S&P500 저가: 5,233.85입니다. S&P500 변동 퍼센티지는 2.30%이고, 환율 종가는 1,373.43입니다. 환율 시가는 1,376.15입니다. 환율 고가는 1,380.26이며 환율 저가는 1,373.70입니다. 환율 변동은 -0.08%입니다.
2024- 08- 09의 S&P500 종가는 5,344.16이며 S&P500 시가는 5,314.66를 기록했습니다. S&P500 고가는 5,358.67였고 S&P500 저가: 5,300.84입니다. S&P500 변동 퍼센티지는 0.47%이고, 환율 종가는 1,364.19입니다. 환율 시가는 1,374.06입니다. 환율 고가는 1,378.06이며 환율 저가는 1,360.68입니다. 환율 변동은 -0.67%입니다.
2024- 08- 12의 S&P500 종가는 5,344.39이며 S&P500 시가는 5,351.88를 기록했습니다. S&P500 고가는 5,371.20였고 S&P500 저가: 5,324.37입니다. S&P500 변동 퍼센티지는 0.00%이고, 환율 종가는 1,368.88입니다. 환율 시가는 1,365.19입니다. 환율 고가는 1,373.94이며 환율 저가는 1,363.11입니다. 환율 변동은 0.34%입니다.
2024- 08- 13의 S&P500 종가는 5,434.43이며 S&P500 시가는 5,376.98를 기록했습니다. S&P500 고가는 5,436.50였고 S&P500 저가: 5,376.98입니다. S&P500 변동 퍼센티지는 1.68%이고, 환율 종가는 1,361.41입니다. 환율 시가는 1,370.33입니다. 환율 고가는 1,373.90이며 환율 저가는 1,361.94입니다. 환율 변동은 -0.55%입니다.
2024- 08- 14의 S&P500 종가는 5,455.21이며 S&P500 시가는 5,442.36를 기록했습니다. S&P500 고가는 5,463.22였고 S&P500 저가: 5,415.91입니다. S&P500 변동 퍼센티지는 0.38%이고, 환율 종가는 1,356.00입니다. 환율 시가는 1,362.94입니다. 환율 고가는 1,365.31이며 환율 저가는 1,353.29입니다. 환율 변동은 -0.40%입니다.
2024- 08- 15의 S&P500 종가는 5,543.22이며 S&P500 시가는 5,501.13를 기록했습니다. S&P500 고가는 5,546.23였고 S&P500 저가: 5,501.13입니다. S&P500 변동 퍼센티지는 1.61%이고, 환율 종가는 1,364.22입니다. 환율 시가는 1,358.30입니다. 환율 고가는 1,367.07이며 환율 저가는 1,354.51입니다. 환율 변동은 0.61%입니다.
2024- 08- 16의 S&P500 종가는 5,554.25이며 S&P500 시가는 5,530.50를 기록했습니다. S&P500 고가는 5,561.98였고 S&P500 저가: 5,525.17입니다. S&P500 변동 퍼센티지는 0.20%이고, 환율 종가는 1,349.11입니다. 환율 시가는 1,365.17입니다. 환율 고가는 1,366.50이며 환율 저가는 1,349.15입니다. 환율 변동은 -1.11%입니다.
2024- 08- 19의 S&P500 종가는 5,608.25이며 S&P500 시가는 5,557.23를 기록했습니다. S&P500 고가는 5,608.30였고 S&P500 저가: 5,550.74입니다. S&P500 변동 퍼센티지는 0.97%이고, 환율 종가는 1,331.64입니다. 환율 시가는 1,350.04입니다. 환율 고가는 1,350.95이며 환율 저가는 1,329.79입니다. 환율 변동은 -1.29%입니다.
2024- 08- 20의 S&P500 종가는 5,597.12이며 S&P500 시가는 5,602.88를 기록했습니다. S&P500 고가는 5,620.51였고 S&P500 저가: 5,585.50입니다. S&P500 변동 퍼센티지는 -0.20%이고, 환율 종가는 1,327.54입니다. 환율 시가는 1,332.35입니다. 환율 고가는 1,337.10이며 환율 저가는 1,324.32입니다. 환율 변동은 -0.31%입니다.
2024- 08- 21의 S&P500 종가는 5,620.85이며 S&P500 시가는 5,603.09를 기록했습니다. S&P500 고가는 5,632.68였고 S&P500 저가: 5,591.57입니다. S&P500 변동 퍼센티지는 0.42%이고, 환율 종가는 1,332.76입니다. 환율 시가는 1,329.29입니다. 환율 고가는 1,340.50이며 환율 저가는 1,326.22입니다. 환율 변동은 0.39%입니다.
2024- 08- 22의 S&P500 종가는 5,570.64이며 S&P500 시가는 5,637.77를 기록했습니다. S&P500 고가는 5,643.22였고 S&P500 저가: 5,560.95입니다. S&P500 변동 퍼센티지는 -0.89%이고, 환율 종가는 1,341.29입니다. 환율 시가는 1,334.28입니다. 환율 고가는 1,344.31이며 환율 저가는 1,331.39입니다. 환율 변동은 0.64%입니다.
2024- 08- 23의 S&P500 종가는 5,634.61이며 S&P500 시가는 5,602.49를 기록했습니다. S&P500 고가는 5,641.82였고 S&P500 저가: 5,585.16입니다. S&P500 변동 퍼센티지는 1.15%이고, 환율 종가는 1,323.43입니다. 환율 시가는 1,342.70입니다. 환율 고가는 1,344.07이며 환율 저가는 1,323.35입니다. 환율 변동은 -1.33%입니다.
2024- 08- 26의 S&P500 종가는 5,616.84이며 S&P500 시가는 5,639.66를 기록했습니다. S&P500 고가는 5,651.62였고 S&P500 저가: 5,602.34입니다. S&P500 변동 퍼센티지는 -0.32%이고, 환율 종가는 1,327.48입니다. 환율 시가는 1,324.78입니다. 환율 고가는 1,329.95이며 환율 저가는 1,317.81입니다. 환율 변동은 0.31%입니다.
2024- 08- 27의 S&P500 종가는 5,625.80이며 S&P500 시가는 5,602.89를 기록했습니다. S&P500 고가는 5,631.18였고 S&P500 저가: 5,593.48입니다. S&P500 변동 퍼센티지는 0.16%이고, 환율 종가는 1,325.77입니다. 환율 시가는 1,328.65입니다. 환율 고가는 1,335.54이며 환율 저가는 1,326.50입니다. 환율 변동은 -0.13%입니다.